# Site settings
title: GeoServices
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  GeoServices are an open REST API for access relational data through the web. 
  One API with direct access to over 24,000 public data via http://opendata.arcgis.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geoservices.github.io" # the base hostname & protocol for your site
twitter_username: esridc
github_username:  esri

# Build settings
markdown: kramdown
